{{- if  (eq .Values.podLogsVersion "v1alpha1") }}
{{- range $name, $config := .Values.pods }}
{{- if $config.podLogs.enabled }}
---
apiVersion: monitoring.grafana.com/v1alpha1
kind: PodLogs
metadata:
  name: {{ $name }}
  namespace: {{ $config.namespace }}
spec:
  pipelineStages:
  - cri: {}
  {{- with $config.podLogs.pipelineStages }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  namespaceSelector:
    matchNames:
    - {{ $config.namespace }}
  selector:
    matchLabels: {{ toYaml $config.labelSelector | nindent 6}}
{{- end }}
{{- end }}
{{- end }}

{{- if (eq .Values.podLogsVersion "v1alpha2") }}
{{- range $name, $config := .Values.pods }}
{{- if $config.podLogs.enabled }}
---
apiVersion: monitoring.grafana.com/v1alpha2
kind: PodLogs
metadata:
  name: {{ $name }}
  namespace: {{ $config.namespace }}
spec:
  namespaceSelector:
    matchLabels:
      name: {{ $config.namespace }}
  selector:
    matchLabels: {{ toYaml $config.labelSelector | nindent 6}}
  relabelings:
    {{- with $config.podLogs.relabelings }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
