{{- $root := . }}
{{- range $cjName, $cj := .Values.cronjobs }}
{{- if $cj.enabled -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $cjName }}
  labels:
  {{- include "archetype.labels" $root | nindent 4 }}
  {{- with $cj.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with $cj.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ $cj.schedule | quote }}
  concurrencyPolicy: {{ $cj.concurrencyPolicy | default "Forbid" }}
  backoffLimit: {{ $cj.backoffLimit | default 0 }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ $cj.serviceAccountName| default "default" }}
          containers:
          {{- toYaml $cj.containers | nindent 10 }}
          restartPolicy: {{ $cj.restartPolicy | default "Never" }}
{{- end }}
{{- end }}
