{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "archetype.name" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "archetype.labelselector" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace }}
    - podSelector:
        matchLabels:
          {{- include "archetype.labelselector" . | nindent 10 }}
    ports:
    {{- range $portName, $portSpec := .Values.ports }}
    - protocol: {{ $portSpec.protocol }}
      port: {{ $portSpec.port }}
    {{- end }}
  {{- if .Values.ingress.enabled }}
  - from:
    - namespaceSelector: {{ toYaml .Values.networkPolicy.ingressControllerNamespaceSelector | nindent 8 }}
    - podSelector: {{ toYaml .Values.networkPolicy.ingressControllerPodSelector | nindent 8 }}
    ports:
    {{- range $portName, $portSpec := .Values.ports }}
    {{- if $portSpec.expose }}
    - protocol: {{ $portSpec.protocol }}
      port: {{ $portSpec.port }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- range .Values.networkPolicy.ingress }}
  - {{ toYaml . | nindent 4 | trim }}
  {{- end }}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  {{- range .Values.networkPolicy.egress }}
  - {{ toYaml . | nindent 4 | trim }}
  {{- end }}
{{- end }}
