{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.rbac.kind }}
metadata:
  name: {{ include "archetype.name" . }}
  labels:
    {{- include "archetype.labels" . | nindent 4 }}
rules:
{{ toYaml .Values.rbac.rules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.rbac.kind }}Binding
metadata:
  name: {{ include "archetype.name" . }}
  labels:
    {{- include "archetype.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.rbac.kind }}
  name: {{ include "archetype.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "archetype.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
