apiVersion: v2
name: archetype
description: A Helm "monochart" for deploying common application patterns

type: application

version: 0.0.1-alpha.7

appVersion: 0.0.0

keywords:
  - app
  - cron
  - deployment
  - statefulset
