image:
  name: "public.ecr.aws/nginx/nginx"
  tag: "alpine"

deployment:
  enabled: true
  kind: "Deployment"
  replicas: 1
  labels: {}
  annotations: {}

pod:
  annotations: {}
  labels: {}
  imagePullSecrets: []
  terminationGracePeriodSeconds: 5
  automountServiceAccountToken: false
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"

resources:
  cpu: "100m"
  memory: "64Mi"
  # Override requests / limits like:
  requests: {}
  limits: {}
  # I strongly recommend you stick to using the memory and cpu options.

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL

healthcheck:
  httpGet:
    path: /
    port: app-port
    scheme: HTTP

ports:
  app-port:
    port: 8080
    protocol: TCP
    expose: true

service:
  enabled: true

ingress:
  enabled: false
  annotations: {}
  className: ""
  host: ""
  paths:
  - "/"

lifecycle: {}
  # preStop:
  #   exec:
  #     command: ["/bin/sh", "-c", "sleep 40"]
  # postStart:
  #   httpGet:
  #     path: /ping
  #     port: 9000
  #     host: localhost
  #     scheme: HTTP

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  # labels: {}
  # annotations: {}
  # maxUnavailable: 1
  # maxUnavailable: 33%
  # minAvailable: 0
  # minAvailable: 25%

args: []

env: []

envFrom: []

initContainers: []

serviceAccount:
  enabled: true
  annotations: {}
  # eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/my-role

extraDeploy: []

podLogs:
  enabled: false

podMonitor:
  enabled: false
  path: /prometheus/metrics
  port: app-port

networkPolicy:
  enabled: true

  ingress: []

  egress: []
  # - to:
  #     - ipBlock:
  #           cidr: 10.1.0.0/24
  #   ports:
  #     - protocol: TCP
  #       port: 5432

  ingressControllerNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: ingress

  ingressControllerPodSelector:
    matchLabels:
      app.kubernetes.io/name: nginx

ciliumNetworkPolicy:
  enabled: false

  ingress: []

  egress: []
  # - toFQDNs:
  #   - matchName: "my-remote-service.com"

  ingressControllerEndpointMatchLabels:
    k8s:io.kubernetes.pod.namespace: ingress
    app.kubernetes.io/name: nginx
