name: Test and Release utility-charts

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup Helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0
        with:
          helmfile-version: "v0.150.0"
          helm-version: "v3.11.0"
          kubectl-version: "1.24.7"
          kubectl-release-date: "2022-10-31"
          additional-helm-plugins: >-
            https://github.com/helm-unittest/helm-unittest

      - name: Lint
        run: helm lint charts/*/

      - name: Test
        run: helm unittest --strict charts/*/

      - name: Release
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_SKIP_EXISTING: "true"
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
