## adapted from https://github.com/marketplace/actions/slack-send

name: shared slack notifier

on:

  workflow_call:
    secrets:
      PLATFORM_ALERT_SLACK_CHANNEL_ID:
        required: true
      SLACK_BOT_TOKEN:
        required: true

jobs:
  post-to-a-slack-channel-on-failure:
    name: post to a slack channel on build failure
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: build
        id: build
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.PLATFORM_ALERT_SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "GitHub Action build result: failure\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: failure\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}